### PR TITLE
Add version argument

### LINKED ISSUE #20: Pull from stable/zenodo
We should change so that we pull data from stable (zenodo) or the bleeding edge as we currently do. Add an argument `stable = TRUE` to pull from zenodo.

### PR DESCRIPTION
**Pull request by jwokaty**
Closes #20.

### CODE REVIEW

**Comment by lgeistlinger** [comment]
This looks all great @jwokaty! I am not sure whether we ultimately need the `httr` dependency and associated dependency stack though. I'd like to keep the package as lightweight as possible.

**Comment by jwokaty** [comment]
I thought it would be better to check if the URL is valid and provide a helpful error message to the user. Is there a better way to do this than using `httr`? (I am still new to R and maybe just don't know a lighter way of doing it.)

**Comment by lgeistlinger** [comment]
Hi @jwokaty I think this small modification below would be a sufficient sanity check for our purposes and avoids the `httr` (and also the `stringr` dependency). 

```
if (grepl("^10.5281/zenodo\\.", version)) {
        version <- sub("^10.5281/zenodo\\.", "", version)
        url <- paste0("https://zenodo.org/record/", version,
                      "/files/full_dump.csv")
        rname <- paste("bugsigdb-zenodo", version, sep = "-")
    } else if (version == "devel") {
        url <- "https://tinyurl.com/3nvzm3fx"
        rname <- paste("bugsigdb", version, sep = "-")
    } else if(grepl("^[0-9a-z]{7}$", version)){
        url <- paste0("https://raw.githubusercontent.com/waldronlab/BugSigDBExports/",
                      version, "/full_dump.csv")
        rname <- paste("bugsigdb-github", version, sep = "-")
    } else {
      stop(paste("Version", version, "does not exist. The version must be a",
                 "DOI, such as '10.5281/zenodo.5819260', a Github hash,",
                 "such as '30383a9', or 'devel'.", sep = " "))
    }
```

**Comment by lgeistlinger** [comment]
And I'd say we push to `devel` only for the beginning and see how it goes. After a while we can either port back to `release` or just wait for the next release which is also not too far away anymore.

**Pull request merged**
